### ISSUE TITLE
npm run dev not fund page

### ISSUE THREAD

**Issue by linsem123** [ruanlin-kylin/vue3-vite-multiple-page#1]
![image](https://user-images.githubusercontent.com/48399559/160242576-3752fcdb-acaf-4093-bce6-897930233b5c.png)

**Comment by ruanlin-kylin** [comment]
readme文件有备注,当同时运行多个模块时,需要在URL后面输入每个模块的上下文才能访问到.

**Comment by ruanlin-kylin** [comment]
> ![图片](https://user-images.githubusercontent.com/48399559/160242576-3752fcdb-acaf-4093-bce6-897930233b5c.png)

readme 文件有备注，当同时运行多个模块时，需要在后面的 URL 输入每个模块的时间访问到。

**Comment by ruanlin-kylin** [comment]
readme 文件有备注，当同时运行多个模块时，需要在 URL 后面加上每个模块的上下文才能访问到。
