### ISSUE TITLE
进入路由后  一刷新就没办法重新加载404 

### ISSUE THREAD

**Issue by qq807061169** [ruanlin-kylin/vue3-vite-multiple-page#2]
http://localhost:5238/main/login
刷新页面后无法重新回到这个登录页面

**Comment by ruanlin-kylin** [comment]
> http://localhost:5238/main/login 刷新页面后无法重新回到这个登录页面

本地开发你可以使用hash路由模式，通过import.meta.env环境变量来区分。
![image](https://user-images.githubusercontent.com/29174640/167390137-61f885e2-f875-4610-84e6-e08f2ce41cd0.png)
生产环境如果要用history模式，需要增加服务器配置。可参考以下官方链接：
https://router.vuejs.org/zh/guide/essentials/history-mode.html#html5-%E6%A8%A1%E5%BC%8F
