### ISSUE TITLE
api封装

### ISSUE THREAD

**Issue by webclientol** [ruanlin-kylin/vue3-vite-multiple-page#3]
配置的页面都需要单独封装axios吗

**Comment by ruanlin-kylin** [comment]
不用哦，axios统一封装放在src目录下，而三个单页模块在modules目录下，每个单页面只需要import 引入外层封装好的 axios 来使用就行了。

**Comment by webclientol** [comment]
谢谢，问题已解决，全局的api可以直接导入使用，但是配置全局的url引入开发环境失效，所以单独配置了.env
